- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - debug:
        msg: "Thank you, my friend!"

    - name: Pause for 5 seconds to build app cache
      ansible.builtin.pause:
        seconds: 5

    - debug:
        msg: "Thank you, my friend!"
